# see http://eslint.org/docs/rules/ for recommended rules
extends: 'eslint:recommended'

rules:
  indent:
    - 2
    - 4
    - SwitchCase: 1
  linebreak-style: [2, unix]
  no-console: [0]
  no-unused-vars: [1]
  # commas go last
  comma-style: [1, last]
  # variable comes before literal in conditional
  yoda: [1, never]
  # dots on same line as property
  dot-location: [1, property]
  # don't allow void operator
  no-void: [1]
  # no space before function paren
  space-before-function-paren: [1, never]
  # prefer a single declaration for vars
  one-var:
    - 1
  space-before-blocks: [1, always]
  # prefer no space between array brackets
  array-bracket-spacing: [1, never]
  # prefer no space between object curly brackets
  object-curly-spacing: [1, never]
  # prefer no space between object prop brackets
  computed-property-spacing: [1, never]
  # prefer camelcase
  # camelcase:
  #   - 1
  #   - properties: always
  # prefer brackets for blocks
  curly: [1]
  no-multi-spaces: [1]
  space-in-parens: [1, never]
  eol-last: [1]
  no-trailing-spaces: [1]
  no-mixed-spaces-and-tabs: [1]
  # Allow but do not force dangling commas.
  comma-dangle: [0]
  # use single quotes
  quotes: [2, single]
  # use semicolons to end statements
  semi: [2, always]

  # warn if function params are reassigned
  no-param-reassign:
    - 1
    - props: false
  # enforce type equality
  eqeqeq: [2]

  no-return-assign: [2, always]
  no-undef-init: [1]
  no-lonely-if: [2]
  no-use-before-define: [2, nofunc]
  # enforce constructor functions are uppercased
  new-cap:
    - 2
    - newIsCap: true
      capIsNew: false



env:
  # allow node env globals
  node: true
  # allow commonjs module definition globals (e.g. require, module.exports)
  commonjs: true
  es6: true
  mocha: true




globals:
