#!/usr/local/bin/node

/**
 * Command-line interface which initiates the frame software.
 */

// dependencies
var program = require('commander');
program
    .version('0.1.0')
    .option('-u, --username <username>', 'Username to which this frame will be linked.')
    .option('-f, --framename <framename>', 'Name for the frame.')
    .option('-d, --apidomain <apidomain>', 'The domain at which the Openframe API is accessible. Defaults to localhost.')
    .option('-p, --apiport <apiport>', 'The port at which the Openframe API is accessible. Defaults to 8888.')
    .option('-P, --apiprotocol <apiprotocol>', 'The domain at which the Openframe API is accessible. Defaults to localhost.')
    .option('-r, --reset', 'If present, reset the configuration, i.e. treat this as an entirely new frame.')
    .parse(process.argv);

// set commandline defaults
if (!program.username) {
    console.log('Username is required.');
    program.outputHelp();
    process.exit();
} else {
    console.log('Starting as ' + program.username);
}

// app dependencies
var config = require('./config');
config('username', program.username);
config('framename', program.framename);
config('api_domain', program.apidomain);
config('api_protocol', program.apiprotocol);
config('api_port', program.apiport);

require('./controller');
require('./extensions');
// Initiate websocket connection to the api server
require('./sockets').connect();